
\begin{verbatim}
>>> print(123)
123

\end{verbatim}


\begin{verbatim}
>>> a = 42
>>> print(a)
42

\end{verbatim}

Test output.

\begin{verbatim}
>>> 2 + 2 * 2 ** 2
10

\end{verbatim}


\begin{verbatim}
>>> for i in range(3):
...     print(i)
...
0
1
2

\end{verbatim}


\begin{verbatim}
>>> for i in range(3):
...     print(i)
...     print(i**2)
...
0
0
1
1
2
4

\end{verbatim}

This code does not work as expected
\begin{verbatim}
for i in range(3):
    print(i)

    print(i**2)
\end{verbatim}


\begin{verbatim}
>>> for i in range(3):
...     print(i)
...
...     print(i**2)
...
0
0
1
1
2
4

\end{verbatim}


\begin{verbatim}
>>> for i in range(3):
...     print(i)
...
0
1
2
>>> print(1 + 2)
3

\end{verbatim}


\begin{verbatim}
>>> for i in range(2):
...     print(i)
...     if i > 0:
...         print("one")
...
0
1
one

\end{verbatim}


\begin{verbatim}
>>> for i in range(3):
...     print(i)
...     if i == 1:
...         raise Exception("foo")
...
0
1
Traceback (most recent call last):
  File "< chunk 8 named None >", line 4, in <module>
Exception: foo
>>> print(42)
42

\end{verbatim}


\begin{verbatim}
>>> def f
  File "< chunk 9 named SyntaxError >", line 1
    def f
        ^
SyntaxError: invalid syntax
>>> print(42)
42

\end{verbatim}


\begin{verbatim}
>>> def f():
...     print(12)
...   print(8)
  File "< chunk 10 named IndentationError >", line 3
    print(8)
           ^
IndentationError: unindent does not match any outer indentation level
>>> print(42)
42

\end{verbatim}

Empty code chunk does not work

\begin{verbatim}
>>>

\end{verbatim}

End

